name: Sync Frontend to AutoCare360

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create sync archive
        id: create_archive
        run: |
          # Create a timestamped tar archive of the frontend code
          tar_file="frontend-sync-$(date +%Y%m%d-%H%M%S).tar.gz"
          echo "Creating archive $tar_file"
          tar --exclude='.git' --exclude='.github' --exclude='node_modules' -czf "$tar_file" .
          echo "archive_name=$tar_file" >> $GITHUB_OUTPUT
      
      - name: Upload archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-sync
          path: ${{ steps.create_archive.outputs.archive_name }}
          retention-days: 14
      
      - name: Create sync notification
        run: |
          echo "Frontend sync complete."
          echo "The frontend code has been packaged as an artifact named 'frontend-sync'."
          echo "Download this artifact and extract it to the 'frontend' directory in the AutoCare360 repository."
          echo "Sync archive: ${{ steps.create_archive.outputs.archive_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
